import React from 'react';

export const BoardCanvas = ({ job }) => (
  <div className="board-canvas">
  	<div id="board">
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
	  	<div className="js-list list-wrapper">
	  		<div className="list js-list-content">
	  			<div className="list-header js-list-header u-clearfix is-menu-shown">
	  				<div className="list-header-target js-editing-target"></div>
	  				<h2 className="list-header-name-assist js-list-name-assist" dir="auto">Première Guerre</h2>
	  				<p className="list-header-num-cards hide js-num-cards">3 cartes</p><div className="list-header-extras"><span className="list-header-extras-subscribe js-list-subscribed hide"><span className="icon-sm icon-subscribe"></span></span><a className="list-header-extras-menu dark-hover js-open-list-menu" href="#"><span className="icon-sm icon-overflow-menu-horizontal"></span></a></div></div><div className="list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable"><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/KKJoELFR/4-l-ascension-de-la-horde"><span className="card-short-id hide">#4</span>L'ascension de la Horde</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/j25mGae5/5-le-dernier-gardien"><span className="card-short-id hide">#5</span>Le dernier Gardien</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div><div className="list-card js-member-droppable ui-droppable"><div className="list-card-cover js-card-cover"></div><span className="icon-sm icon-edit list-card-operation dark-hover js-open-quick-card-editor js-card-menu"></span><div className="list-card-stickers-area hide"><div className="stickers js-card-stickers"></div></div><div className="list-card-details"><div className="list-card-labels js-card-labels"></div><a className="list-card-title js-card-name" dir="auto" href="/c/O8PT0kd4/10-l-heure-des-tenebres"><span className="card-short-id hide">#10</span>L'heure des Ténèbres</a><div className="badges"><span></span></div><div className="list-card-members js-list-card-members"></div></div><p className="list-card-dropzone">Faites glisser un fichier pour l'ajouter.</p></div></div><a className="open-card-composer js-open-card-composer" href="#">Ajouter une carte…</a></div></div>
  	</div>
  </div>
);

BoardCanvas.propTypes = {
  job: React.PropTypes.object,
};
